version: '3'

volumes:
  mysql-database:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    ports:
      - "8280:8080"
    volumes:
      - ./src/:/go/src
    tty: true
  db:
    image: mysql:8
    ports:
      - 3326:3306
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
